# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_card.ipynb.

# %% auto 0
__all__ = ['Card']

# %% ../nbs/00_card.ipynb 2
from fastcore.utils import *
from fastcore.test import *

# %% ../nbs/00_card.ipynb 5
import sys, urllib.request

# %% ../nbs/00_card.ipynb 16
class Card:
    "A playing card, created by passing in `rank`  and `suit` "
    def __init__(self,
                 suit:int, # An index into `suits`
                 rank:int): # An index into `ranks`
        self.suit,self.rank=suit,rank     
    def __str__(self):return f"{ranks[self.rank]}{suits[self.suit]}"
    __repr__=__str__
    

# %% ../nbs/00_card.ipynb 28
@patch
def __eq__(self:Card,a:Card): return (self.suit,self.rank)==(a.suit,a.rank)

# %% ../nbs/00_card.ipynb 33
@patch
def __lt__(self:Card,a:Card): return (self.suit,self.rank)<(a.suit,a.rank)

# %% ../nbs/00_card.ipynb 36
@patch
def __gt__(self:Card,a:Card): return (self.suit,self.rank)>(a.suit,a.rank)
